name: Build React Native Android and iOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # -------------------------
  # Android Build
  # -------------------------
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup Yarn 3
        run: |
          corepack enable
          corepack prepare yarn@3.6.4 --activate

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install dependencies
        run: |
          yarn install --immutable
          cd android
          chmod +x gradlew

      - name: Setup Android SDK + NDK + CMake
        uses: android-actions/setup-android@v2
        with:
          api-level: 33
          target: android-33
          ndk-version: 26.1.10909125  # matches your android/build.gradle
          cmake-version: 3.22.1

      - name: Build Android Release APK
        run: |
          cd android
          ./gradlew assembleRelease -PnodeExecutable=$(which node)

      - name: Upload Android APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-android
          path: android/app/build/outputs/apk/release/app-release.apk

  # -------------------------
  # iOS Build
  # -------------------------
  build-ios:
    runs-on: macos-latest
    needs: build-android

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup Yarn 3
        run: |
          corepack enable
          corepack prepare yarn@3.6.4 --activate

      - name: Install dependencies
        run: |
          yarn install --immutable
          cd ios
          pod install --repo-update

      - name: Build iOS App (Unsigned)
        run: |
          cd ios
          xcodebuild \
            -workspace DateTimePicker.xcworkspace \
            -scheme DateTimePicker \
            -configuration Release \
            -sdk iphoneos \
            -archivePath $PWD/build/DateTimePicker.xcarchive \
            archive

          xcodebuild -exportArchive \
            -archivePath $PWD/build/
